config/routes.rb
Rails.application.routes.draw do
    root to: 'homes#top'
    devise_for :users
    resources :users, only:[:index, :show, :edit, :update, :destroy]
    resources :foods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :foods, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource) 
    foods_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    
    def new
        @food = Food.new
    end
    
    def create
        @food = Food.new(food_params)
        @food.save
        redirect_to foods_path
    end
    
    def index
        @foods = Food.all
        @today = Date.current.strftime('%Y-%m-%d')
    end
    
    def show
        @food = Food.find(params[:id])
    end
    
    def edit
        @food = Food.find(params[:id])
    end
    
    def destroy
        food = Food.find(params[:id])
        food.destroy
        redirect_to root_path
    end
    
    def edit
        @food = Food.find(params[:id])
    end
    
    def update
        food = Food.find(params[:id])
        food.update(food_params)
        redirect_to food_path(food.id)
    end
    
    private

    def food_params
        params.require(:food).permit(:title, :image, :expiration, :user)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user)
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/edit.html.erb
<h1>編集画面</h1>
<%= form_with model:@food, local:true do |f| %>
    <%= f.attachment_field :image %>
    <%= f.text_field :title %>
    <%= f.date_select :expiration %>
    <%= f.submit '保存する' %>
<% end %>
<%= link_to '一覧', foods_path %>
<%= link_to '削除', food_path(@food.id), method: :delete, data: {confirm: "削除しますか？"} %>

app/views/foods/index.html.erb
<h1>食品一覧</h1>

<%= link_to '新規保存', new_food_path %>

<% @foods.each do |food| %>
    <%= link_to food_path(food.id) do %>
        <% if @food_expiration == @today %>
            <%= attachment_image_tag food, :image, format: 'jpeg', size: "100x100", class:'change-background' %>
        <% else %>
            <%= attachment_image_tag food, :image, format: 'jpeg', size: "100x100" %>
        <% end %>
    <% end %>
    
    <%= food.title %>
    <%= food.expiration %>
<% end %>

app/views/foods/new.html.erb
<h1>食品を保存する</h1>
<%= form_with model:@food, local:true do |f| %>
    <%= f.attachment_field :image %>
    <%= f.text_field :title %>
    <%= f.date_select :expiration %>
    <%= f.submit '保存する' %>
<% end %>

app/views/foods/show.html.erb
<h1>詳細ページ</h1>
<%= link_to edit_food_path(@food.id) do %>
    <%= attachment_image_tag @food, :image, format: 'jpeg', size: "100x100" %>
<% end %>
<% @food.title %>
<% @food.expiration %>

<%= link_to '編集', edit_food_path(@food.id) %>
<%= link_to '一覧', foods_path %>
<%= link_to '削除', food_path(@food), method: :delete, data: {confirm: "削除しますか？"} %>

app/views/homes/top.html.erb
<div class="container-md">
  <div class="row">
    <div class="col-md">
      <h1 class="text-center mt-3 mb-3">トップページです</h1>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid bg-primary" style="height: 80px">
      <div class="row h-100">
        <div class="col-4 mr-auto d-flex align-items-center" style="font-size:2rem">
          <i class="fas fa-utensils"></i>
          <%= link_to 'FOOD', foods_path, class:'text-light' %>
        </div>
        <div class="col-2 d-flex align-items-center justify-content-between ml-auto" style="font-size:1rem">
          <% if user_signed_in? %>
            <i class="fas fa-users">
            <%= link_to 'ユーザー', users_path, class:'text-light' %>
            </i>
            <i class="fas fa-sign-out-alt">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:'text-light' %>
            </i>
          <% else %>
            <i class="fas fa-user-edit">
            <%= link_to "新規登録", new_user_registration_path, class:'text-light' %>
            </i>
            <i class="fas fa-sign-in-alt">
            <%= link_to "ログイン", new_user_session_path, class:'text-light' %>
            </i>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="container-md">
  <div class="row">
    <div class="col-md mt-3 mb-3">
      <h1 class="text-center">ユーザー一覧</h1>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col col-md-8">
      <table class="table text-center">
      <thead>
        <tr>
          <th scope="col" style="width:20%">ID</th>
          <th scope="col" style="width:40%">ProfileImage</th>
          <th scope="col" style="width:40%">Name</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <th scope="row" class="align-middle"><%= user.id %></th>
          <td>
            <%= link_to user_path(user.id) do %>
            <%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.png" %>
            <% end %>
          </td>
          <td class="align-middle"><%= link_to user.name, user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-md">
  <div class="row">
    <div class="col-md mt-3 mb-3">
      <h1 class="text-center">プロフィール</h1>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col col-md-6">
      <table class="table text-center">
      <thead>
        <tr>
          <th scope="col" style="width:50%">ProfileImage</th>
          <th scope="col" style="width:50%">Name</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.png" %></td>
          <td class="align-middle"><%= @user.name %></td>
        </tr>
      </tbody>
    </table>
    </div>
  </div>
</div>